version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # not created automatically for version updates so only security ones are created
    pull-request-branch-name:
      separator: "-"