PREFIX = "/v1"
PREFIX_ORG = PREFIX + "/organization"
PREFIX_PROJECT = PREFIX + "/project"
PREFIX_MISC = PREFIX + "/misc"
PREFIX_ZERO_SHOT = PREFIX + "/zero-shot"
PREFIX_ATTRIBUTE = PREFIX + "/attribute"
PREFIX_EMBEDDING = PREFIX + "/embedding"
PREFIX_NOTIFICATION = PREFIX + "/notification"
