"""Progress Field attributes

Revision ID: 03d19eada266
Revises: bb87177d46b5
Create Date: 2023-05-15 14:36:17.587964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d19eada266'
down_revision = 'bb87177d46b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'progress')
    # ### end Alembic commands ###
