"""Added llm_config for project

Revision ID: 059fb8192d6c
Revises: e0fa50dd6350
Create Date: 2024-06-18 11:21:22.702956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059fb8192d6c'
down_revision = 'e0fa50dd6350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('llm_config', sa.JSON(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'llm_config', schema='cognition')
    # ### end Alembic commands ###
