"""Added incognito mode to conversations

Revision ID: 059f0d62a6b9
Revises: 24ca8432bd8b
Create Date: 2025-10-15 14:17:59.216693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059f0d62a6b9'
down_revision = '24ca8432bd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('incognito_mode', sa.Boolean(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'incognito_mode', schema='cognition')
    # ### end Alembic commands ###
