"""New diff columns

Revision ID: 05bbef1eec3f
Revises: f8c313f63a36
Create Date: 2024-10-28 07:46:38.865170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bbef1eec3f'
down_revision = 'f8c313f63a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_logs', sa.Column('scope_dict_diff_new', sa.JSON(), nullable=True), schema='cognition')
    op.add_column('pipeline_logs', sa.Column('record_dict_diff_new', sa.JSON(), nullable=True), schema='cognition')
    op.add_column('message', sa.Column('scope_dict_diff_new', sa.JSON(), nullable=True), schema='cognition')

    # note that migration of field values is done in cognition
    # after the release another one is needed to remove the old columns

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_logs', 'record_dict_diff_new', schema='cognition')
    op.drop_column('pipeline_logs', 'scope_dict_diff_new', schema='cognition')
    op.drop_column('message', 'scope_dict_diff_new', schema='cognition')
    # ### end Alembic commands ###
