"""Additional data on the embeddings table

Revision ID: 0714589d508e
Revises: 73798599a917
Create Date: 2023-08-03 13:21:49.464532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0714589d508e'
down_revision = '73798599a917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('additional_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding', 'additional_data')
    # ### end Alembic commands ###
