"""add settings root_dir

Revision ID: 092eaee6c491
Revises: 5e4455c984fe
Create Date: 2025-02-17 14:48:48.544312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092eaee6c491'
down_revision = '5e4455c984fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphrag_index', sa.Column('settings', sa.JSON(), nullable=True), schema='cognition')
    op.add_column('graphrag_index', sa.Column('root_dir', sa.String(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphrag_index', 'root_dir', schema='cognition')
    op.drop_column('graphrag_index', 'settings', schema='cognition')
    # ### end Alembic commands ###
