"""Add Thread association

Revision ID: 094dd28a1d8d
Revises: d02bf381e3ed
Create Date: 2025-11-15 19:07:22.805825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '094dd28a1d8d'
down_revision = 'd02bf381e3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_mail_thread_association',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('thread_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['global.inbox_mail_thread.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='global'
    )
    op.create_index(op.f('ix_global_inbox_mail_thread_association_thread_id'), 'inbox_mail_thread_association', ['thread_id'], unique=False, schema='global')
    op.create_index(op.f('ix_global_inbox_mail_thread_association_user_id'), 'inbox_mail_thread_association', ['user_id'], unique=False, schema='global')
    op.add_column('inbox_mail_thread', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True), schema='global')
    op.drop_index('idx_inbox_thread_participants_gin', table_name='inbox_mail_thread', schema='global')
    op.create_index(op.f('ix_global_inbox_mail_thread_created_by'), 'inbox_mail_thread', ['created_by'], unique=False, schema='global')
    op.create_foreign_key(None, 'inbox_mail_thread', 'user', ['created_by'], ['id'], source_schema='global', ondelete='CASCADE')
    op.drop_column('inbox_mail_thread', 'participant_ids', schema='global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail_thread', sa.Column('participant_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True), schema='global')
    op.drop_constraint(None, 'inbox_mail_thread', schema='global', type_='foreignkey')
    op.drop_index(op.f('ix_global_inbox_mail_thread_created_by'), table_name='inbox_mail_thread', schema='global')
    op.create_index('idx_inbox_thread_participants_gin', 'inbox_mail_thread', ['participant_ids'], unique=False, schema='global')
    op.drop_column('inbox_mail_thread', 'created_by', schema='global')
    op.drop_index(op.f('ix_global_inbox_mail_thread_association_user_id'), table_name='inbox_mail_thread_association', schema='global')
    op.drop_index(op.f('ix_global_inbox_mail_thread_association_thread_id'), table_name='inbox_mail_thread_association', schema='global')
    op.drop_table('inbox_mail_thread_association', schema='global')
    # ### end Alembic commands ###
