"""adds_playground_question

Revision ID: 0c8eb3ff1c71
Revises: ac97442726d2
Create Date: 2025-02-04 09:48:41.971287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c8eb3ff1c71'
down_revision = 'ac97442726d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_question',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('embedding_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('record_ids', sa.JSON(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['embedding_id'], ['embedding.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playground_question_created_by'), 'playground_question', ['created_by'], unique=False)
    op.create_index(op.f('ix_playground_question_embedding_id'), 'playground_question', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_playground_question_project_id'), 'playground_question', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playground_question_project_id'), table_name='playground_question')
    op.drop_index(op.f('ix_playground_question_embedding_id'), table_name='playground_question')
    op.drop_index(op.f('ix_playground_question_created_by'), table_name='playground_question')
    op.drop_table('playground_question')
    # ### end Alembic commands ###
