"""adds cognition dataroom table

Revision ID: 0cf68a39bff2
Revises: 51faeba6987c
Create Date: 2024-09-01 18:50:52.390356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0cf68a39bff2'
down_revision = '51faeba6987c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataroom",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["cognition.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )

    op.create_index(
        op.f("ix_cognition_dataroom_project_id"),
        "dataroom",
        ["project_id"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_dataroom_created_by"),
        "dataroom",
        ["created_by"],
        unique=False,
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cognition_dataroom_project_id"),
        table_name="dataroom",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_dataroom_created_by"),
        table_name="dataroom",
        schema="cognition",
    )
    op.drop_table("dataroom", schema="cognition")
    # ### end Alembic commands ###
