"""Adds attribute name and scope to tokenization table

Revision ID: 0e0e4aeac7eb
Revises: da902ad27b4a
Create Date: 2023-01-16 15:52:55.334364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0e4aeac7eb'
down_revision = 'da902ad27b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_tokenization_task', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('record_tokenization_task', sa.Column('attribute_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_tokenization_task', 'attribute_name')
    op.drop_column('record_tokenization_task', 'scope')
    # ### end Alembic commands ###
