"""Add inbox mail

Revision ID: 0ea9ab7cb60f
Revises: 85bb3ebee137
Create Date: 2025-11-21 13:43:44.056253

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0ea9ab7cb60f"
down_revision = "85bb3ebee137"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_mail_thread",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("is_important", sa.Boolean(), nullable=True),
        sa.Column("progress_state", sa.String(), nullable=True),
        sa.Column("support_owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("is_admin_support_thread", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["support_owner_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_created_by"),
        "inbox_mail_thread",
        ["created_by"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_organization_id"),
        "inbox_mail_thread",
        ["organization_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_support_owner_id"),
        "inbox_mail_thread",
        ["support_owner_id"],
        unique=False,
        schema="global",
    )
    op.create_table(
        "inbox_mail",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("sender_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("thread_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["sender_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["global.inbox_mail_thread.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_sender_id"),
        "inbox_mail",
        ["sender_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_id"),
        "inbox_mail",
        ["thread_id"],
        unique=False,
        schema="global",
    )
    op.create_table(
        "inbox_mail_thread_association",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("thread_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("unread_mail_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["global.inbox_mail_thread.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_association_thread_id"),
        "inbox_mail_thread_association",
        ["thread_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_association_user_id"),
        "inbox_mail_thread_association",
        ["user_id"],
        unique=False,
        schema="global",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_association_user_id"),
        table_name="inbox_mail_thread_association",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_association_thread_id"),
        table_name="inbox_mail_thread_association",
        schema="global",
    )
    op.drop_table("inbox_mail_thread_association", schema="global")
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_id"), table_name="inbox_mail", schema="global"
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_sender_id"), table_name="inbox_mail", schema="global"
    )
    op.drop_table("inbox_mail", schema="global")
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_support_owner_id"),
        table_name="inbox_mail_thread",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_organization_id"),
        table_name="inbox_mail_thread",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_created_by"),
        table_name="inbox_mail_thread",
        schema="global",
    )
    op.drop_table("inbox_mail_thread", schema="global")
    # ### end Alembic commands ###
