"""adds attribute `additional_config` and llm_config

Revision ID: 10c48793371d
Revises: eb5ecbee5090
Create Date: 2025-01-15 17:08:30.137845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c48793371d'
down_revision = 'eb5ecbee5090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('additional_config', sa.JSON(), nullable=True, comment='used when data_type == LLM_RESPONSE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'additional_config')
    # ### end Alembic commands ###
