"""add state meta_data

Revision ID: 136f2f1af860
Revises: 21bf4b4fbe3b
Create Date: 2024-10-02 09:26:02.067883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136f2f1af860'
down_revision = '21bf4b4fbe3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_reference', sa.Column('state', sa.String(), nullable=True), schema='cognition')
    op.add_column('file_reference', sa.Column('meta_data', sa.JSON(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_reference', 'meta_data', schema='cognition')
    op.drop_column('file_reference', 'state', schema='cognition')
    # ### end Alembic commands ###
