"""adds etl new attributes

Revision ID: 15f133dd208b
Revises: 04cd434ed6eb
Create Date: 2025-12-11 22:34:07.966633

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15f133dd208b"
down_revision = "04cd434ed6eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etl_task",
        sa.Column("full_config_hash", sa.String(), nullable=True),
        schema="global",
    )
    op.add_column(
        "etl_task", sa.Column("is_stale", sa.Boolean(), nullable=True), schema="global"
    )
    op.add_column(
        "etl_task", sa.Column("llm_ops", sa.JSON(), nullable=True), schema="global"
    )
    op.add_column(
        "etl_task",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_etl_task_full_config_hash"),
        "etl_task",
        ["full_config_hash"],
        unique=False,
        schema="global",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_global_etl_task_full_config_hash"),
        table_name="etl_task",
        schema="global",
    )
    op.drop_column("etl_task", "updated_at", schema="global")
    op.drop_column("etl_task", "llm_ops", schema="global")
    op.drop_column("etl_task", "is_stale", schema="global")
    op.drop_column("etl_task", "full_config_hash", schema="global")
    # ### end Alembic commands ###
