"""new org column

Revision ID: 199a0d8aefbe
Revises: 24ca8432bd8b
Create Date: 2025-10-20 07:36:33.488523

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "199a0d8aefbe"
down_revision = "24ca8432bd8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("track_user_message_count", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("messages_created_this_month", sa.BigInteger(), nullable=True)
    )

    op.create_table(
        "timed_executions",
        sa.Column("time_key", sa.String(), nullable=False),
        sa.Column("last_executed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("time_key"),
        sa.UniqueConstraint("time_key"),
        schema="global",
    )
    connection = op.get_bind()

    update_dataset_sql = """
        UPDATE public.user
        SET messages_created_this_month = 0
        WHERE messages_created_this_month IS NULL
    """
    connection.execute(update_dataset_sql)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "messages_created_this_month")
    op.drop_column("organization", "track_user_message_count")
    op.drop_table("timed_executions", schema="global")
    # ### end Alembic commands ###
