"""new org column

Revision ID: 199a0d8aefbe
Revises: c6d1cbcccb41
Create Date: 2025-10-20 07:36:33.488523

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "199a0d8aefbe"
down_revision = "c6d1cbcccb41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("messages_created_this_month", sa.BigInteger(), nullable=True)
    )

    op.create_table(
        "timed_executions",
        sa.Column("time_key", sa.String(), nullable=False),
        sa.Column("last_executed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("time_key"),
        sa.UniqueConstraint("time_key"),
        schema="global",
    )
    connection = op.get_bind()

    update_dataset_sql = """
        UPDATE public.user
        SET messages_created_this_month = 0
        WHERE messages_created_this_month IS NULL
    """
    connection.execute(update_dataset_sql)
    op.drop_column("user", "oidc_identifier")
    op.create_unique_constraint(None, "timed_executions", ["time_key"], schema="global")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "messages_created_this_month")
    op.drop_table("timed_executions", schema="global")
    op.drop_constraint(None, "timed_executions", schema="global", type_="unique")
    op.add_column(
        "user",
        sa.Column("oidc_identifier", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
