"""Adds agreements, gdpr flags and platform support for embeddings

Revision ID: 1a25c862801f
Revises: 03d19eada266
Create Date: 2023-06-06 13:58:16.634066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a25c862801f'
down_revision = '03d19eada266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('xfkey', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('xftype', sa.String(), nullable=True),
    sa.Column('terms_text', sa.String(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_project_id'), 'agreement', ['project_id'], unique=False)
    op.create_index(op.f('ix_agreement_user_id'), 'agreement', ['user_id'], unique=False)
    op.create_index(op.f('ix_agreement_xfkey'), 'agreement', ['xfkey'], unique=False)
    op.create_index(op.f('ix_agreement_xftype'), 'agreement', ['xftype'], unique=False)
    op.add_column('embedding', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('embedding', sa.Column('api_token', sa.String(), nullable=True))
    op.add_column('embedding', sa.Column('model', sa.String(), nullable=True))
    op.add_column('embedding', sa.Column('platform', sa.String(), nullable=True))
    op.create_index(op.f('ix_embedding_created_by'), 'embedding', ['created_by'], unique=False)
    op.create_foreign_key(None, 'embedding', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('organization', sa.Column('gdpr_compliant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'gdpr_compliant')
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.drop_index(op.f('ix_embedding_created_by'), table_name='embedding')
    op.drop_column('embedding', 'platform')
    op.drop_column('embedding', 'model')
    op.drop_column('embedding', 'api_token')
    op.drop_column('embedding', 'created_by')
    op.drop_index(op.f('ix_agreement_xftype'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_xfkey'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_user_id'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_project_id'), table_name='agreement')
    op.drop_table('agreement')
    # ### end Alembic commands ###
