"""adds consumption logs

Revision ID: 1e96826f3bd8
Revises: 754dd15f2c9c
Create Date: 2024-03-12 16:31:18.080718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e96826f3bd8'
down_revision = '754dd15f2c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_log',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('strategy_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('project_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['cognition.conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['cognition.message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['cognition.project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['cognition.strategy.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_consumption_log_conversation_id'), 'consumption_log', ['conversation_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_consumption_log_created_by'), 'consumption_log', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_consumption_log_message_id'), 'consumption_log', ['message_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_consumption_log_organization_id'), 'consumption_log', ['organization_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_consumption_log_project_id'), 'consumption_log', ['project_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_consumption_log_strategy_id'), 'consumption_log', ['strategy_id'], unique=False, schema='cognition')
    op.add_column('project', sa.Column('state', sa.String(), nullable=True), schema='cognition')
    op.drop_column('project', 'wizard_running', schema='cognition')
    op.add_column('strategy', sa.Column('complexity', sa.String(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'complexity', schema='cognition')
    op.add_column('project', sa.Column('wizard_running', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='cognition')
    op.drop_column('project', 'state', schema='cognition')
    op.drop_index(op.f('ix_cognition_consumption_log_strategy_id'), table_name='consumption_log', schema='cognition')
    op.drop_index(op.f('ix_cognition_consumption_log_project_id'), table_name='consumption_log', schema='cognition')
    op.drop_index(op.f('ix_cognition_consumption_log_organization_id'), table_name='consumption_log', schema='cognition')
    op.drop_index(op.f('ix_cognition_consumption_log_message_id'), table_name='consumption_log', schema='cognition')
    op.drop_index(op.f('ix_cognition_consumption_log_created_by'), table_name='consumption_log', schema='cognition')
    op.drop_index(op.f('ix_cognition_consumption_log_conversation_id'), table_name='consumption_log', schema='cognition')
    op.drop_table('consumption_log', schema='cognition')
    # ### end Alembic commands ###
