"""Release notifications table

Revision ID: 24ca8432bd8b
Revises: 9e606cf1f902
Create Date: 2025-10-01 08:49:37.899217

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "24ca8432bd8b"
down_revision = "9e606cf1f902"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_release_notification_created_by"),
        "release_notification",
        ["created_by"],
        unique=False,
        schema="global",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_global_release_notification_created_by"),
        table_name="release_notification",
        schema="global",
    )
    op.drop_table("release_notification", schema="global")
    # ### end Alembic commands ###
