"""remove user activity

Revision ID: 2c0029684bd7
Revises: 7aa933ec5de9
Create Date: 2024-11-25 14:48:25.980269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c0029684bd7'
down_revision = '7aa933ec5de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_activity_created_by', table_name='user_activity')
    op.drop_table('user_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('activity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('from_backup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='user_activity_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_activity_pkey')
    )
    op.create_index('ix_user_activity_created_by', 'user_activity', ['created_by'], unique=False)
    # ### end Alembic commands ###
