"""Test migration

Revision ID: 2c063e918272
Revises: 6f13fbbdf3fa
Create Date: 2024-07-23 12:38:54.405841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c063e918272'
down_revision = '6f13fbbdf3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment_variable', sa.Column('test_column', sa.String(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment_variable', 'test_column', schema='cognition')
    # ### end Alembic commands ###
