"""adds websearch

Revision ID: 2e61bd14e425
Revises: 6f674eb4928f
Create Date: 2023-12-11 22:11:51.517352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e61bd14e425'
down_revision = '6f674eb4928f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('websearch_step',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('strategy_step_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column("config", sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='websearch_step_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['cognition.project.id'], name='websearch_step_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_step_id'], ['cognition.strategy_step.id'], name='websearch_step_strategy_step_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='websearch_step_pkey'),
    schema='cognition'
    )

    op.create_index('ix_cognition_websearch_step_strategy_step_id', 'websearch_step', ['strategy_step_id'], unique=False, schema='cognition')
    op.create_index('ix_cognition_websearch_step_project_id', 'websearch_step', ['project_id'], unique=False, schema='cognition')
    op.create_index('ix_cognition_websearch_step_created_by', 'websearch_step', ['created_by'], unique=False, schema='cognition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_cognition_websearch_step_created_by'), table_name='websearch_step', schema='cognition')
    op.drop_index(op.f('ix_cognition_websearch_step_project_id'), table_name='websearch_step', schema='cognition')
    op.drop_index(op.f('ix_cognition_websearch_step_strategy_step_id'), table_name='websearch_step', schema='cognition')
    op.drop_table('websearch_step', schema='cognition')

    # ### end Alembic commands ###
