"""add graphrag index

Revision ID: 2f46377be599
Revises: eb5ecbee5090
Create Date: 2025-02-07 12:30:03.455560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f46377be599'
down_revision = 'eb5ecbee5090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphrag_index',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_graphrag_index_created_by'), 'graphrag_index', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_graphrag_index_organization_id'), 'graphrag_index', ['organization_id'], unique=False, schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cognition_graphrag_index_organization_id'), table_name='graphrag_index', schema='cognition')
    op.drop_index(op.f('ix_cognition_graphrag_index_created_by'), table_name='graphrag_index', schema='cognition')
    op.drop_table('graphrag_index', schema='cognition')
    # ### end Alembic commands ###
