"""update integration sharepoint size dtype

Revision ID: 312568866ac4
Revises: 3e6633b3fa0a
Create Date: 2025-08-28 10:00:04.377743

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "312568866ac4"
down_revision = "3e6633b3fa0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sharepoint",
        "size",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        # postgresql_using="size::bigint",
        schema="integration",
    )


def downgrade():
    op.alter_column(
        "sharepoint",
        "size",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        # postgresql_using="size::integer",
        schema="integration",
    )
