"""Adds limits to orga

Revision ID: 3b118e1e02cb
Revises: a5c341d1a7ef
Create Date: 2023-03-01 10:49:53.348290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b118e1e02cb'
down_revision = 'a5c341d1a7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('max_rows', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('max_cols', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('max_char_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'max_char_count')
    op.drop_column('organization', 'max_cols')
    op.drop_column('organization', 'max_rows')
    # ### end Alembic commands ###
