"""Added schema data_manager

Revision ID: 3d0f69f9c513
Revises: 706d5611a73e
Create Date: 2024-07-09 08:14:48.808354

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d0f69f9c513"
down_revision = "706d5611a73e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema data_manager")
    op.create_table(
        "organization_questions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data_manager",
    )
    op.create_index(
        op.f("ix_data_manager_organization_questions_organization_id"),
        "organization_questions",
        ["organization_id"],
        unique=False,
        schema="data_manager",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_manager_organization_questions_organization_id"),
        table_name="organization_questions",
        schema="data_manager",
    )
    op.drop_table("organization_questions", schema="data_manager")
    op.execute("drop schema data_manager")
    # ### end Alembic commands ###
