"""Adds smart routing

Revision ID: 3e59ce51739c
Revises: b7b9f7de1013
Create Date: 2024-09-02 12:32:23.493855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e59ce51739c'
down_revision = 'b7b9f7de1013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_requirement',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('strategy_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_input', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['cognition.project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['cognition.strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_strategy_requirement_created_by'), 'strategy_requirement', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_strategy_requirement_project_id'), 'strategy_requirement', ['project_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_strategy_requirement_strategy_id'), 'strategy_requirement', ['strategy_id'], unique=False, schema='cognition')
    op.create_table('strategy_requirement_mapping_option',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('strategy_requirement_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['cognition.project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_requirement_id'], ['cognition.strategy_requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_strategy_requirement_mapping_option_created_by'), 'strategy_requirement_mapping_option', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_strategy_requirement_mapping_option_project_id'), 'strategy_requirement_mapping_option', ['project_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_strategy_requirement_mapping_option_strategy_requirement_id'), 'strategy_requirement_mapping_option', ['strategy_requirement_id'], unique=False, schema='cognition')
    op.add_column('pipeline_logs', sa.Column('iteration_number', sa.Integer(), nullable=True), schema='cognition')
    
    # change to alter to prevent data loss
    # op.add_column('project', sa.Column('operator_routing_config', sa.JSON(), nullable=True), schema='cognition')
    # op.drop_column('project', 'operator_routing_source_code', schema='cognition')
    op.alter_column('project', 'operator_routing_source_code', new_column_name='operator_routing_config', schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # change to alter to prevent data loss
    op.alter_column('project', 'operator_routing_config', new_column_name='operator_routing_source_code', schema='cognition')
    # op.add_column('project', sa.Column('operator_routing_source_code', sa.VARCHAR(), autoincrement=False, nullable=True), schema='cognition')
    # op.drop_column('project', 'operator_routing_config', schema='cognition')
    op.drop_column('pipeline_logs', 'iteration_number', schema='cognition')
    op.drop_index(op.f('ix_cognition_strategy_requirement_mapping_option_strategy_requirement_id'), table_name='strategy_requirement_mapping_option', schema='cognition')
    op.drop_index(op.f('ix_cognition_strategy_requirement_mapping_option_project_id'), table_name='strategy_requirement_mapping_option', schema='cognition')
    op.drop_index(op.f('ix_cognition_strategy_requirement_mapping_option_created_by'), table_name='strategy_requirement_mapping_option', schema='cognition')
    op.drop_table('strategy_requirement_mapping_option', schema='cognition')
    op.drop_index(op.f('ix_cognition_strategy_requirement_strategy_id'), table_name='strategy_requirement', schema='cognition')
    op.drop_index(op.f('ix_cognition_strategy_requirement_project_id'), table_name='strategy_requirement', schema='cognition')
    op.drop_index(op.f('ix_cognition_strategy_requirement_created_by'), table_name='strategy_requirement', schema='cognition')
    op.drop_table('strategy_requirement', schema='cognition')
    # ### end Alembic commands ###
