"""sum table

Revision ID: 3e6633b3fa0a
Revises: 580fd6de4f15
Create Date: 2025-08-19 08:18:28.043370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e6633b3fa0a'
down_revision = '580fd6de4f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sums_table',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sum_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='global'
    )
    op.create_index(op.f('ix_global_sums_table_sum_key'), 'sums_table', ['sum_key'], unique=False, schema='global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_sums_table_sum_key'), table_name='sums_table', schema='global')
    op.drop_table('sums_table', schema='global')
    # ### end Alembic commands ###
