"""add pat etl table

Revision ID: 46023692929d
Revises: eb5ecbee5090
Create Date: 2025-02-11 13:55:03.170678

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "46023692929d"
down_revision = "eb5ecbee5090"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_access_token_etl",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["cognition.markdown_dataset.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_personal_access_token_etl_created_by"),
        "personal_access_token_etl",
        ["created_by"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_personal_access_token_etl_dataset_id"),
        "personal_access_token_etl",
        ["dataset_id"],
        unique=False,
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cognition_personal_access_token_etl_dataset_id"),
        table_name="personal_access_token_etl",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_personal_access_token_etl_created_by"),
        table_name="personal_access_token_etl",
        schema="cognition",
    )
    op.drop_table("personal_access_token_etl", schema="cognition")
    # ### end Alembic commands ###
