"""Add admin query message summary

Revision ID: 49122cddaf65
Revises: 626c2c026041
Create Date: 2025-09-24 14:52:02.478956

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49122cddaf65"
down_revision = "626c2c026041"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_query_message_summary",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("total_conversations", sa.Integer(), nullable=True),
        sa.Column("total_messages", sa.Integer(), nullable=True),
        sa.Column("messages_via_api", sa.Integer(), nullable=True),
        sa.Column("messages_via_ui", sa.Integer(), nullable=True),
        sa.Column("messages_via_macro", sa.Integer(), nullable=True),
        sa.Column("confidential_messages", sa.Integer(), nullable=True),
        sa.Column("kern_user_messages", sa.Integer(), nullable=True),
        sa.Column("deleted_messages_by_user", sa.Integer(), nullable=True),
        sa.Column("deleted_messages_by_system", sa.Integer(), nullable=True),
        sa.Column("incognito_messages", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["cognition.project.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            "day",
            name="unique_admin_query_msg_activity_summary",
        ),
        schema="cognition",
    )
    op.add_column(
        "message",
        sa.Column("initiated_via", sa.String(), nullable=True),
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "initiated_via", schema="cognition")
    op.drop_table("admin_query_message_summary", schema="cognition")
    # ### end Alembic commands ###
