"""add cognition group management

Revision ID: 4da42978f669
Revises: 5a22c0039b8e
Create Date: 2025-06-03 13:37:57.131295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4da42978f669'
down_revision = '5a22c0039b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_group_created_by'), 'group', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_group_organization_id'), 'group', ['organization_id'], unique=False, schema='cognition')
    op.create_table('group_member',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['cognition.group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_group_member_group_id'), 'group_member', ['group_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_group_member_user_id'), 'group_member', ['user_id'], unique=False, schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cognition_group_member_user_id'), table_name='group_member', schema='cognition')
    op.drop_index(op.f('ix_cognition_group_member_group_id'), table_name='group_member', schema='cognition')
    op.drop_table('group_member', schema='cognition')
    op.drop_index(op.f('ix_cognition_group_organization_id'), table_name='group', schema='cognition')
    op.drop_index(op.f('ix_cognition_group_created_by'), table_name='group', schema='cognition')
    op.drop_table('group', schema='cognition')
    # ### end Alembic commands ###
