"""Added sound and notifications settings to users

Revision ID: 4ffb627479d3
Revises: 60a3d04181f7
Create Date: 2026-01-21 08:46:20.544543

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ffb627479d3"
down_revision = "60a3d04181f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("sound_settings", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("notification_settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "notification_settings")
    op.drop_column("user", "sound_settings")
    # ### end Alembic commands ###
