"""sets md file etl task id null on deletion

Revision ID: 5186966ea4db
Revises: 15f133dd208b
Create Date: 2025-12-15 07:59:30.702200

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5186966ea4db"
down_revision = "15f133dd208b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "markdown_file_etl_task_id_fkey",
        "markdown_file",
        schema="cognition",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "markdown_file",
        "etl_task",
        ["etl_task_id"],
        ["id"],
        source_schema="cognition",
        referent_schema="global",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "markdown_file", schema="cognition", type_="foreignkey")
    op.create_foreign_key(
        "markdown_file_etl_task_id_fkey",
        "markdown_file",
        "etl_task",
        ["etl_task_id"],
        ["id"],
        source_schema="cognition",
        referent_schema="global",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
