"""adds project type column

Revision ID: 51faeba6987c
Revises: b7b9f7de1013
Create Date: 2024-08-31 09:31:21.034370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51faeba6987c'
down_revision = 'b7b9f7de1013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("type", sa.String(), nullable=True),
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "type", schema="cognition")
    # ### end Alembic commands ###
