"""Added started_at and finished_at on attribute and embedding table

Revision ID: 546e5cd7feaa
Revises: 3b118e1e02cb
Create Date: 2023-03-06 12:21:19.095488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546e5cd7feaa'
down_revision = '3b118e1e02cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('attribute', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('embedding', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('embedding', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding', 'finished_at')
    op.drop_column('embedding', 'started_at')
    op.drop_column('attribute', 'finished_at')
    op.drop_column('attribute', 'started_at')
    # ### end Alembic commands ###
