"""adds cognition actions table

Revision ID: 588c5e9f90aa
Revises: 7edb03b88c03
Create Date: 2024-04-27 08:59:52.899815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '588c5e9f90aa'
down_revision = '7edb03b88c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True, unique=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["cognition.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(op.f("ix_action_created_at"), "action", ["created_at"], unique=False, schema="cognition")
    op.create_index(op.f("ix_action_created_by"), "action", ["created_by"], unique=False, schema="cognition")
    op.create_index(op.f("ix_action_project_id"), "action", ["project_id"], unique=False, schema="cognition")

    op.add_column(
        "conversation",
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=True),
        schema="cognition",
    )

    op.create_table(
        "question_node",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("root", sa.Boolean(), nullable=True),
        sa.Column("position_x", sa.Integer(), nullable=True),
        sa.Column("position_y", sa.Integer(), nullable=True),
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["cognition.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(op.f("ix_question_node_created_at"), "question_node", ["created_at"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_node_created_by"), "question_node", ["created_by"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_node_project_id"), "question_node", ["project_id"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_node_to_node_id"), "question_node", ["action_id"], unique=False, schema="cognition")

    op.create_table(
        "question_edge",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("from_node_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("to_node_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("condition", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["cognition.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["from_node_id"], ["cognition.question_node.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"], ["cognition.question_node.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(op.f("ix_question_edge_created_at"), "question_edge", ["created_at"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_edge_created_by"), "question_edge", ["created_by"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_edge_from_node_id"), "question_edge", ["from_node_id"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_edge_project_id"), "question_edge", ["project_id"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_edge_to_node_id"), "question_edge", ["to_node_id"], unique=False, schema="cognition")
    op.create_index(op.f("ix_question_edge_action_id"), "question_edge", ["action_id"], unique=False, schema="cognition")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_question_edge_to_node_id"), table_name="question_edge", schema="cognition")
    op.drop_index(op.f("ix_question_edge_project_id"), table_name="question_edge", schema="cognition")
    op.drop_index(op.f("ix_question_edge_from_node_id"), table_name="question_edge", schema="cognition")
    op.drop_index(op.f("ix_question_edge_created_by"), table_name="question_edge", schema="cognition")
    op.drop_index(op.f("ix_question_edge_created_at"), table_name="question_edge", schema="cognition")
    op.drop_index(op.f("ix_question_edge_action_id"), table_name="question_edge", schema="cognition")
    op.drop_table("question_edge", schema="cognition")

    op.drop_index(op.f("ix_question_node_to_node_id"), table_name="question_node", schema="cognition")
    op.drop_index(op.f("ix_question_node_project_id"), table_name="question_node", schema="cognition")
    op.drop_index(op.f("ix_question_node_created_by"), table_name="question_node", schema="cognition")
    op.drop_index(op.f("ix_question_node_created_at"), table_name="question_node", schema="cognition")
    op.drop_index(op.f("ix_question_node_action_id"), table_name="question_node", schema="cognition")
    op.drop_table("question_node", schema="cognition")

    op.drop_column("conversation", "action_id", schema="cognition")

    op.drop_index(op.f("ix_action_project_id"), table_name="action", schema="cognition")
    op.drop_index(op.f("ix_action_created_by"), table_name="action", schema="cognition")
    op.drop_index(op.f("ix_action_created_at"), table_name="action", schema="cognition")
    op.drop_table("action", schema="cognition")
    # ### end Alembic commands ###
