"""Added oidc identifier column to users table

Revision ID: 5a22c0039b8e
Revises: eb96f9b82cc1
Create Date: 2025-05-21 08:56:58.320996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a22c0039b8e'
down_revision = '96fbb404381e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oidc_identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'oidc_identifier')
    # ### end Alembic commands ###
