"""Adds service version table

Revision ID: 5b3a4deea1c4
Revises: 992352f4c1f9
Create Date: 2022-09-05 13:34:55.863128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "5b3a4deea1c4"
down_revision = "992352f4c1f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_version",
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("installed_version", sa.String(), nullable=True),
        sa.Column("remote_version", sa.String(), nullable=True),
        sa.Column("last_checked", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("service"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_version")
