"""adds etl task table

Revision ID: 5f8de6fcce30
Revises: 24ca8432bd8b
Create Date: 2025-10-26 20:43:48.216324

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f8de6fcce30"
down_revision = "24ca8432bd8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etl_task",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("markdown_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sharepoint_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("tokenizer", sa.String(), nullable=True),
        sa.Column("extract_config", sa.JSON(), nullable=True),
        sa.Column("split_config", sa.JSON(), nullable=True),
        sa.Column("transform_config", sa.JSON(), nullable=True),
        sa.Column("load_config", sa.JSON(), nullable=True),
        sa.Column("notify_config", sa.JSON(), nullable=True),
        sa.Column("llm_config", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["markdown_file_id"], ["cognition.markdown_file.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sharepoint_file_id"], ["integration.sharepoint.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_etl_task_created_by"),
        "etl_task",
        ["created_by"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_etl_task_markdown_file_id"),
        "etl_task",
        ["markdown_file_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_etl_task_organization_id"),
        "etl_task",
        ["organization_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_etl_task_sharepoint_file_id"),
        "etl_task",
        ["sharepoint_file_id"],
        unique=False,
        schema="global",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_global_etl_task_sharepoint_file_id"),
        table_name="etl_task",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_etl_task_organization_id"),
        table_name="etl_task",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_etl_task_markdown_file_id"),
        table_name="etl_task",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_etl_task_created_by"), table_name="etl_task", schema="global"
    )
    op.drop_table("etl_task", schema="global")
    # ### end Alembic commands ###
