"""Autologout field to users

Revision ID: 626c2c026041
Revises: de396670d10f
Create Date: 2025-09-16 10:29:38.062540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626c2c026041'
down_revision = 'de396670d10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auto_logout_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_logout_minutes')
    # ### end Alembic commands ###
