"""Admin logs on org checkbox

Revision ID: 63364f1fe61d
Revises: 7edb03b88c03
Create Date: 2024-05-13 11:11:50.171745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63364f1fe61d'
down_revision = '7edb03b88c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('log_admin_requests', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'log_admin_requests')
    # ### end Alembic commands ###
