"""test migration

Revision ID: 66798b5eccc7
Revises: b7b9f7de1013
Create Date: 2024-08-13 12:29:22.609443

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66798b5eccc7"
down_revision = "881102ae15f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
