"""adds cognition group management

Revision ID: 6868ac66ea92
Revises: 36f087da55b1
Create Date: 2025-06-26 12:58:16.408919

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6868ac66ea92"
down_revision = "36f087da55b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_group_created_by"),
        "group",
        ["created_by"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_group_organization_id"),
        "group",
        ["organization_id"],
        unique=False,
        schema="cognition",
    )
    op.create_table(
        "group_member",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["cognition.group.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_group_member_group_id"),
        "group_member",
        ["group_id"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_group_member_user_id"),
        "group_member",
        ["user_id"],
        unique=False,
        schema="cognition",
    )
    op.add_column("user", sa.Column("oidc_identifier", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "oidc_identifier")
    op.drop_index(
        op.f("ix_cognition_group_member_user_id"),
        table_name="group_member",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_group_member_group_id"),
        table_name="group_member",
        schema="cognition",
    )
    op.drop_table("group_member", schema="cognition")
    op.drop_index(
        op.f("ix_cognition_group_organization_id"),
        table_name="group",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_group_created_by"), table_name="group", schema="cognition"
    )
    op.drop_table("group", schema="cognition")
    # ### end Alembic commands ###
