"""adds max folder size

Revision ID: 6f13fbbdf3fa
Revises: 706d5611a73e
Create Date: 2024-07-05 09:12:12.691404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f13fbbdf3fa'
down_revision = '706d5611a73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('max_folder_size_mb', sa.Float(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'max_folder_size_mb', schema='cognition')
    # ### end Alembic commands ###
