"""feedback message type

Revision ID: 6f674eb4928f
Revises: a2b5235166cb
Create Date: 2023-12-09 19:16:28.035626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f674eb4928f'
down_revision = 'a2b5235166cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('message', sa.Column('feedback_value', sa.String(), nullable=True), schema='cognition')
    op.add_column('message', sa.Column('feedback_category', sa.String(), nullable=True), schema='cognition')
    op.add_column('strategy_step', sa.Column('execute_if_source_code', sa.String(), nullable=True), schema='cognition')
    op.drop_column('message', 'positive_feedback', schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('message', sa.Column('positive_feedback', sa.Boolean(), nullable=True), schema='cognition')
    op.drop_column('strategy_step', 'execute_if_source_code', schema='cognition')
    op.drop_column('message', 'feedback_category', schema='cognition')
    op.drop_column('message', 'feedback_value', schema='cognition')

    # ### end Alembic commands ###
