"""edit global conversation share

Revision ID: 723c17fa280b
Revises: ac3d026a15b1
Create Date: 2025-10-27 12:45:55.456652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723c17fa280b'
down_revision = 'ac3d026a15b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_global_share_public_token_key', 'conversation_global_share', schema='cognition', type_='unique')
    op.drop_column('conversation_global_share', 'is_active', schema='cognition')
    op.drop_column('conversation_global_share', 'warning_acknowledged', schema='cognition')
    op.drop_column('conversation_global_share', 'public_token', schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_global_share', sa.Column('public_token', sa.VARCHAR(), autoincrement=False, nullable=False), schema='cognition')
    op.add_column('conversation_global_share', sa.Column('warning_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='cognition')
    op.add_column('conversation_global_share', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='cognition')
    op.create_unique_constraint('conversation_global_share_public_token_key', 'conversation_global_share', ['public_token'], schema='cognition')
    # ### end Alembic commands ###
