"""add integration sharepoint property sync

Revision ID: 7334713b30a6
Revises: 6868ac66ea92
Create Date: 2025-07-29 12:31:04.171629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7334713b30a6'
down_revision = '6868ac66ea92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharepoint_property_sync',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('integration_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('logs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['cognition.integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_property_sync_created_by'), 'sharepoint_property_sync', ['created_by'], unique=False)
    op.create_index(op.f('ix_sharepoint_property_sync_integration_id'), 'sharepoint_property_sync', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharepoint_property_sync_integration_id'), table_name='sharepoint_property_sync')
    op.drop_index(op.f('ix_sharepoint_property_sync_created_by'), table_name='sharepoint_property_sync')
    op.drop_table('sharepoint_property_sync')
    # ### end Alembic commands ###
