"""Adds global websocket table

Revision ID: 754dd15f2c9c
Revises: 7de3c19cddcf
Create Date: 2024-02-16 06:33:18.628812

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "754dd15f2c9c"
down_revision = "7de3c19cddcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema global")
    op.create_table(
        "websocket_access",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("in_use", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_websocket_access_created_by"),
        "websocket_access",
        ["created_by"],
        unique=False,
        schema="global",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_global_websocket_access_created_by"),
        table_name="websocket_access",
        schema="global",
    )
    op.drop_table("websocket_access", schema="global")
    op.execute("drop schema global")
    # ### end Alembic commands ###
