"""Kratos data

Revision ID: 7aa933ec5de9
Revises: 05bbef1eec3f
Create Date: 2024-11-19 16:04:00.539685

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7aa933ec5de9"
down_revision = "05bbef1eec3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=True))
    op.add_column("user", sa.Column("verified", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("metadata_public", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("sso_provider", sa.String(), nullable=True))
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "sso_provider")
    op.drop_column("user", "metadata_public")
    op.drop_column("user", "created_at")
    op.drop_column("user", "verified")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
