"""adds synopsis table

Revision ID: 7daca1f5efc7
Revises: daf80476b9cc
Create Date: 2023-12-30 17:41:33.516169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7daca1f5efc7'
down_revision = 'daf80476b9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('synopsis_spreadsheet',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dataset_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('filter_attribute_name', sa.String(), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['cognition.markdown_dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['cognition.project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )

    op.create_index(op.f('ix_cognition_synopsis_spreadsheet_created_by'), 'synopsis_spreadsheet', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_synopsis_spreadsheet_dataset_id'), 'synopsis_spreadsheet', ['dataset_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_synopsis_spreadsheet_project_id'), 'synopsis_spreadsheet', ['project_id'], unique=False, schema='cognition')

    op.create_table('synopsis_spreadsheet_row',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('spreadsheet_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['cognition.synopsis_spreadsheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )

    op.create_index(op.f('ix_cognition_synopsis_spreadsheet_row_created_by'), 'synopsis_spreadsheet_row', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_synopsis_spreadsheet_row_spreadsheet_id'), 'synopsis_spreadsheet_row', ['spreadsheet_id'], unique=False, schema='cognition')

    op.add_column('conversation', sa.Column('synopsis_spreadsheet_row_id', sa.String(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'synopsis_spreadsheet_row_id', schema='cognition')

    op.drop_index(op.f('ix_cognition_synopsis_spreadsheet_row_spreadsheet_id'), table_name='synopsis_spreadsheet_row', schema='cognition')
    op.drop_index(op.f('ix_cognition_synopsis_spreadsheet_row_created_by'), table_name='synopsis_spreadsheet_row', schema='cognition')

    op.drop_table('synopsis_spreadsheet_row', schema='cognition')

    op.drop_index(op.f('ix_cognition_synopsis_spreadsheet_project_id'), table_name='synopsis_spreadsheet', schema='cognition')
    op.drop_index(op.f('ix_cognition_synopsis_spreadsheet_dataset_id'), table_name='synopsis_spreadsheet', schema='cognition')
    op.drop_index(op.f('ix_cognition_synopsis_spreadsheet_created_by'), table_name='synopsis_spreadsheet', schema='cognition')

    op.drop_table('synopsis_spreadsheet', schema='cognition')    
    # ### end Alembic commands ###
