"""adds team tables

Revision ID: 7de3c19cddcf
Revises: 6b7c123b3e52
Create Date: 2024-02-09 12:26:58.403086

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7de3c19cddcf"
down_revision = "6b7c123b3e52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_created_by"), "team", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_team_organization_id"), "team", ["organization_id"], unique=False
    )
    op.create_table(
        "team_member",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_member_created_by"), "team_member", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_team_member_team_id"), "team_member", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_member_user_id"), "team_member", ["user_id"], unique=False
    )
    op.create_table(
        "team_resource",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resource_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_resource_created_by"),
        "team_resource",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_resource_resource_id"),
        "team_resource",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_resource_team_id"), "team_resource", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_resource_team_id"), table_name="team_resource")
    op.drop_index(op.f("ix_team_resource_resource_id"), table_name="team_resource")
    op.drop_index(op.f("ix_team_resource_created_by"), table_name="team_resource")
    op.drop_table("team_resource")
    op.drop_index(op.f("ix_team_member_user_id"), table_name="team_member")
    op.drop_index(op.f("ix_team_member_team_id"), table_name="team_member")
    op.drop_index(op.f("ix_team_member_created_by"), table_name="team_member")
    op.drop_table("team_member")
    op.drop_index(op.f("ix_team_organization_id"), table_name="team")
    op.drop_index(op.f("ix_team_created_by"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
