"""adds_cognition_facts_grouping_attribute

Revision ID: 7edb03b88c03
Revises: 4861b97fcd5d
Create Date: 2024-04-09 14:43:22.793156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edb03b88c03'
down_revision = '4861b97fcd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('facts_grouping_attribute', sa.String(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'facts_grouping_attribute', schema='cognition')
    # ### end Alembic commands ###
