"""add project conv share settings

Revision ID: 85bb3ebee137
Revises: 77f1ea22a633
Create Date: 2025-11-03 12:55:02.413126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bb3ebee137'
down_revision = '77f1ea22a633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('allow_conversation_sharing_organization', sa.Boolean(), nullable=True), schema='cognition')
    op.add_column('project', sa.Column('allow_conversation_sharing_global', sa.Boolean(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'allow_conversation_sharing_global', schema='cognition')
    op.drop_column('project', 'allow_conversation_sharing_organization', schema='cognition')
    # ### end Alembic commands ###
