"""Adds created attributes columns

Revision ID: 87f463aa5112
Revises: 5b3a4deea1c4
Create Date: 2022-09-13 08:22:52.181427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "87f463aa5112"
down_revision = "5b3a4deea1c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attribute", sa.Column("user_created", sa.Boolean(), nullable=True))
    op.add_column("attribute", sa.Column("source_code", sa.String(), nullable=True))
    op.add_column("attribute", sa.Column("state", sa.String(), nullable=True))
    op.add_column("attribute", sa.Column("logs", sa.ARRAY(sa.String()), nullable=True))
    op.add_column(
        "embedding",
        sa.Column("attribute_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "embedding_attribute_id_fkey",
        "embedding",
        "attribute",
        ["attribute_id"],
        ["id"],
        ondelete="CASCADE",
    ),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attribute", "user_created")
    op.drop_column("attribute", "source_code")
    op.drop_column("attribute", "state")
    op.drop_column("attribute", "logs")
    op.drop_column("embedding", "attribute_id")
    op.drop_constraint("embedding_attribute_id_fkey", "embedding", type_="foreignkey")
    # ### end Alembic commands ###
