"""rework task queue

Revision ID: 881102ae15f8
Revises: 37d138040614
Create Date: 2024-08-08 12:57:27.648167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '881102ae15f8'
down_revision = '37d138040614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_queue',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('task_info', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='global'
    )
    op.create_index(op.f('ix_global_task_queue_created_by'), 'task_queue', ['created_by'], unique=False, schema='global')
    op.create_index(op.f('ix_global_task_queue_organization_id'), 'task_queue', ['organization_id'], unique=False, schema='global')
    op.drop_index('ix_task_queue_created_by', table_name='task_queue')
    op.drop_table('task_queue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_queue',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='task_queue_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='task_queue_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_queue_pkey')
    )
    op.create_index('ix_task_queue_created_by', 'task_queue', ['created_by'], unique=False)
    op.drop_index(op.f('ix_global_task_queue_organization_id'), table_name='task_queue', schema='global')
    op.drop_index(op.f('ix_global_task_queue_created_by'), table_name='task_queue', schema='global')
    op.drop_table('task_queue', schema='global')
    # ### end Alembic commands ###
