"""Unread mail count thread

Revision ID: 8b89db0d41fd
Revises: c95b049b0779
Create Date: 2025-11-17 14:28:02.843729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b89db0d41fd'
down_revision = 'c95b049b0779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail_thread_association', sa.Column('unread_mail_count', sa.Integer(), nullable=True), schema='global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox_mail_thread_association', 'unread_mail_count', schema='global')
    # ### end Alembic commands ###
