"""user and org

Revision ID: 8f202e150862
Revises: e3e108cd4b22
Create Date: 2026-01-26 16:10:22.600805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f202e150862'
down_revision = 'e3e108cd4b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('light_user_config', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('messages_created_today', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'messages_created_today')
    op.drop_column('organization', 'light_user_config')
    # ### end Alembic commands ###
