"""Add admin query message summary

Revision ID: 94fd265646c0
Revises: de396670d10f
Create Date: 2025-09-24 13:07:02.549717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94fd265646c0'
down_revision = 'de396670d10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_query_message_summary',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('messages_via_api', sa.Integer(), nullable=True),
    sa.Column('messages_via_ui', sa.Integer(), nullable=True),
    sa.Column('messages_via_macro', sa.Integer(), nullable=True),
    sa.Column('confidential_messages', sa.Integer(), nullable=True),
    sa.Column('kern_user_messages', sa.Integer(), nullable=True),
    sa.Column('deleted_messages_by_user', sa.Integer(), nullable=True),
    sa.Column('deleted_messages_by_system', sa.Integer(), nullable=True),
    sa.Column('incognito_messages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('day', 'organization_id', 'project_id'),
    sa.UniqueConstraint('organization_id', 'project_id', 'day', name='unique_admin_query_msg_activity_summary'),
    schema='cognition'
    )
    op.add_column('message', sa.Column('initiated_via', sa.String(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'initiated_via', schema='cognition')
    op.drop_table('admin_query_message_summary', schema='cognition')
    # ### end Alembic commands ###
