"""adds interface type to cognition project

Revision ID: 961f37b6aab8
Revises: 491ea68a7baf
Create Date: 2023-11-28 16:57:34.827621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '961f37b6aab8'
down_revision = '491ea68a7baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('interface_type', sa.String(), nullable=True), schema='cognition')
    op.add_column('project', sa.Column('enable_query_enrichment', sa.Boolean(), nullable=True), schema='cognition')
    op.add_column('strategy_step', sa.Column('progress_text', sa.String(), nullable=True), schema='cognition')
    op.add_column('strategy_step', sa.Column('enable_emissions', sa.Boolean(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_step', 'enable_emissions', schema='cognition')
    op.drop_column('strategy_step', 'progress_text', schema='cognition')
    op.drop_column('project', 'enable_query_enrichment', schema='cognition')
    op.drop_column('project', 'interface_type', schema='cognition')
    # ### end Alembic commands ###
