"""adds data blocks

Revision ID: 9a8abc15a493
Revises: 4ffb627479d3
Create Date: 2026-01-20 23:08:30.530156

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9a8abc15a493"
down_revision = "4ffb627479d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_block",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("sql_config", sa.JSON(), nullable=True),
        sa.Column("sql_data", sa.ARRAY(sa.JSON()), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_block_created_by"), "data_block", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_data_block_organization_id"),
        "data_block",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_block_project_id"), "data_block", ["project_id"], unique=False
    )
    op.create_table(
        "data_block_attributes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("data_block_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("data_type", sa.String(), nullable=True),
        sa.Column("is_primary_key", sa.Boolean(), nullable=True),
        sa.Column("relative_position", sa.Integer(), nullable=True),
        sa.Column("user_created", sa.Boolean(), nullable=True),
        sa.Column("source_code", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("logs", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column(
            "additional_config",
            sa.JSON(),
            nullable=True,
            comment="used when data_type == LLM_RESPONSE",
        ),
        sa.ForeignKeyConstraint(
            ["data_block_id"], ["data_block.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_block_attributes_data_block_id"),
        "data_block_attributes",
        ["data_block_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_block_attributes_data_block_id"),
        table_name="data_block_attributes",
    )
    op.drop_table("data_block_attributes")
    op.drop_index(op.f("ix_data_block_project_id"), table_name="data_block")
    op.drop_index(op.f("ix_data_block_organization_id"), table_name="data_block")
    op.drop_index(op.f("ix_data_block_created_by"), table_name="data_block")
    op.drop_table("data_block")
    # ### end Alembic commands ###
