"""adds integration providers

Revision ID: 9d146e05e1ee
Revises: eb96f9b82cc1
Create Date: 2025-05-15 13:25:34.353936

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d146e05e1ee"
down_revision = "eb96f9b82cc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_organization_access",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("integration_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_integration_organization_access_created_by"),
        "integration_organization_access",
        ["created_by"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_integration_organization_access_organization_id"),
        "integration_organization_access",
        ["organization_id"],
        unique=False,
        schema="cognition",
    )
    op.create_table(
        "third_party_integration",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("llm_config", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_third_party_integration_created_by"),
        "third_party_integration",
        ["created_by"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_third_party_integration_project_id"),
        "third_party_integration",
        ["project_id"],
        unique=False,
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cognition_third_party_integration_project_id"),
        table_name="third_party_integration",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_third_party_integration_created_by"),
        table_name="third_party_integration",
        schema="cognition",
    )
    op.drop_table("third_party_integration", schema="cognition")
    op.drop_index(
        op.f("ix_cognition_integration_organization_access_organization_id"),
        table_name="integration_organization_access",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_integration_organization_access_created_by"),
        table_name="integration_organization_access",
        schema="cognition",
    )
    op.drop_table("integration_organization_access", schema="cognition")
    # ### end Alembic commands ###
