"""new message field

Revision ID: 9e606cf1f902
Revises: 626c2c026041
Create Date: 2025-09-29 12:02:05.914392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e606cf1f902'
down_revision = '626c2c026041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('additional_data', sa.JSON(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'additional_data', schema='cognition')
    # ### end Alembic commands ###
