"""Adds key support for upload task

Revision ID: 9e61fe319903
Revises: 03d19eada266
Create Date: 2023-06-19 13:11:26.347729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e61fe319903'
down_revision = '03d19eada266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_task', sa.Column('key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_task', 'key')
    # ### end Alembic commands ###
