"""adds iteration number to pipeline logs

Revision ID: 9f527dd70d1e
Revises: 706d5611a73e
Create Date: 2024-07-09 09:46:54.139282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f527dd70d1e'
down_revision = '706d5611a73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pipeline_logs",
        sa.Column("iteration_number", sa.Integer(), nullable=True),
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pipeline_logs", "iteration_number", schema="cognition")
    # ### end Alembic commands ###
