"""Add conversation shares

Revision ID: a071bf6f3800
Revises: 199a0d8aefbe
Create Date: 2025-10-30 09:35:16.913089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a071bf6f3800'
down_revision = '199a0d8aefbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_global_share',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shared_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['cognition.conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_conversation_global_share_conversation_id'), 'conversation_global_share', ['conversation_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_conversation_global_share_shared_by'), 'conversation_global_share', ['shared_by'], unique=False, schema='cognition')
    op.create_table('conversation_share',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shared_with', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shared_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('can_copy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['cognition.conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_conversation_share_conversation_id'), 'conversation_share', ['conversation_id'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_conversation_share_shared_by'), 'conversation_share', ['shared_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_conversation_share_shared_with'), 'conversation_share', ['shared_with'], unique=False, schema='cognition')
    op.drop_table('timed_executions', schema='global')
    op.add_column('user', sa.Column('oidc_identifier', sa.String(), nullable=True))
    op.drop_column('user', 'messages_created_this_month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('messages_created_this_month', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('user', 'oidc_identifier')
    op.create_table('timed_executions',
    sa.Column('time_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('time_key', name='timed_executions_pkey'),
    sa.UniqueConstraint('time_key', name='timed_executions_time_key_key'),
    schema='global'
    )
    op.drop_index(op.f('ix_cognition_conversation_share_shared_with'), table_name='conversation_share', schema='cognition')
    op.drop_index(op.f('ix_cognition_conversation_share_shared_by'), table_name='conversation_share', schema='cognition')
    op.drop_index(op.f('ix_cognition_conversation_share_conversation_id'), table_name='conversation_share', schema='cognition')
    op.drop_table('conversation_share', schema='cognition')
    op.drop_index(op.f('ix_cognition_conversation_global_share_shared_by'), table_name='conversation_global_share', schema='cognition')
    op.drop_index(op.f('ix_cognition_conversation_global_share_conversation_id'), table_name='conversation_global_share', schema='cognition')
    op.drop_table('conversation_global_share', schema='cognition')
    # ### end Alembic commands ###
