"""test-migration

Revision ID: a61e5a5b6414
Revises: 0d587af700ce
Create Date: 2024-07-31 09:37:27.524858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61e5a5b6414'
down_revision = '0d587af700ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
