"""add graphrag index

Revision ID: ab45734be591
Revises: 32f92724c13c
Create Date: 2025-02-27 12:38:55.549604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab45734be591'
down_revision = '32f92724c13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphrag_index',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('root_dir', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_graphrag_index_created_by'), 'graphrag_index', ['created_by'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_graphrag_index_organization_id'), 'graphrag_index', ['organization_id'], unique=False, schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cognition_graphrag_index_organization_id'), table_name='graphrag_index', schema='cognition')
    op.drop_index(op.f('ix_cognition_graphrag_index_created_by'), table_name='graphrag_index', schema='cognition')
    op.drop_table('graphrag_index', schema='cognition')
    # ### end Alembic commands ###
