"""remove project id task queue

Revision ID: af5c30d91685
Revises: 0d587af700ce
Create Date: 2024-08-04 15:42:26.747671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af5c30d91685'
down_revision = '0d587af700ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_execution_summary',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('creation_month', sa.Date(), nullable=True),
    sa.Column('macro_type', sa.String(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('processed_files_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'creation_month', 'macro_type', name='unique_macro_summary'),
    schema='cognition'
    )
    op.create_index(op.f('ix_cognition_macro_execution_summary_creation_month'), 'macro_execution_summary', ['creation_month'], unique=False, schema='cognition')
    op.create_index(op.f('ix_cognition_macro_execution_summary_organization_id'), 'macro_execution_summary', ['organization_id'], unique=False, schema='cognition')
    op.add_column('task_queue', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('task_queue_project_id_fkey', 'task_queue', type_='foreignkey')
    op.create_foreign_key(None, 'task_queue', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_queue', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_queue', sa.Column('project_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_queue', type_='foreignkey')
    op.create_foreign_key('task_queue_project_id_fkey', 'task_queue', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_queue', 'organization_id')
    op.drop_index(op.f('ix_cognition_macro_execution_summary_organization_id'), table_name='macro_execution_summary', schema='cognition')
    op.drop_index(op.f('ix_cognition_macro_execution_summary_creation_month'), table_name='macro_execution_summary', schema='cognition')
    op.drop_table('macro_execution_summary', schema='cognition')
    # ### end Alembic commands ###
