"""Remove todesktop

Revision ID: b482df6324a1
Revises: d454676ee76f
Create Date: 2026-05-28 08:27:58.774302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b482df6324a1'
down_revision = 'd454676ee76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_version')
    op.drop_column('user', 'one_drive_path')
    op.drop_column('user', 'notification_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notification_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('one_drive_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('app_version',
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('installed_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remote_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_checked', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('service', name='app_version_pkey')
    )
    # ### end Alembic commands ###
