"""Change inbox model

Revision ID: b59188cf5526
Revises: ebf4435d83f8
Create Date: 2025-11-12 10:01:36.389914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b59188cf5526'
down_revision = 'ebf4435d83f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail', sa.Column('sender_id', postgresql.UUID(as_uuid=True), nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('recipient_id', postgresql.UUID(as_uuid=True), nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('other_recipient_ids', sa.JSON(), nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('thread_id', postgresql.UUID(as_uuid=True), nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('is_important', sa.Boolean(), nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('being_working_on', sa.Boolean(), nullable=True), schema='global')
    op.drop_index('ix_global_inbox_mail_child_id', table_name='inbox_mail', schema='global')
    op.create_index(op.f('ix_global_inbox_mail_recipient_id'), 'inbox_mail', ['recipient_id'], unique=False, schema='global')
    op.create_index(op.f('ix_global_inbox_mail_sender_id'), 'inbox_mail', ['sender_id'], unique=False, schema='global')
    op.create_index(op.f('ix_global_inbox_mail_thread_id'), 'inbox_mail', ['thread_id'], unique=False, schema='global')
    op.drop_constraint('inbox_mail_child_id_fkey', 'inbox_mail', schema='global', type_='foreignkey')
    op.create_foreign_key(None, 'inbox_mail', 'user', ['sender_id'], ['id'], source_schema='global', ondelete='SET NULL')
    op.create_foreign_key(None, 'inbox_mail', 'user', ['recipient_id'], ['id'], source_schema='global', ondelete='CASCADE')
    op.drop_column('inbox_mail', 'mark_as_important', schema='global')
    op.drop_column('inbox_mail', 'being_worked_on', schema='global')
    op.drop_column('inbox_mail', 'child_id', schema='global')
    op.drop_column('inbox_mail', 'send_from', schema='global')
    op.drop_column('inbox_mail', 'send_to', schema='global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail', sa.Column('send_to', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('send_from', sa.VARCHAR(), autoincrement=False, nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('child_id', postgresql.UUID(), autoincrement=False, nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('being_worked_on', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='global')
    op.add_column('inbox_mail', sa.Column('mark_as_important', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='global')
    op.drop_constraint(None, 'inbox_mail', schema='global', type_='foreignkey')
    op.drop_constraint(None, 'inbox_mail', schema='global', type_='foreignkey')
    op.create_foreign_key('inbox_mail_child_id_fkey', 'inbox_mail', 'inbox_mail', ['child_id'], ['id'], source_schema='global', referent_schema='global', ondelete='SET NULL')
    op.drop_index(op.f('ix_global_inbox_mail_thread_id'), table_name='inbox_mail', schema='global')
    op.drop_index(op.f('ix_global_inbox_mail_sender_id'), table_name='inbox_mail', schema='global')
    op.drop_index(op.f('ix_global_inbox_mail_recipient_id'), table_name='inbox_mail', schema='global')
    op.create_index('ix_global_inbox_mail_child_id', 'inbox_mail', ['child_id'], unique=False, schema='global')
    op.drop_column('inbox_mail', 'being_working_on', schema='global')
    op.drop_column('inbox_mail', 'is_important', schema='global')
    op.drop_column('inbox_mail', 'thread_id', schema='global')
    op.drop_column('inbox_mail', 'other_recipient_ids', schema='global')
    op.drop_column('inbox_mail', 'recipient_id', schema='global')
    op.drop_column('inbox_mail', 'sender_id', schema='global')
    # ### end Alembic commands ###
