"""add macro execution summary

Revision ID: b7b9f7de1013
Revises: 881102ae15f8
Create Date: 2024-07-29 16:27:34.759906

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b7b9f7de1013"
down_revision = "881102ae15f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_execution_summary",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("creation_month", sa.Date(), nullable=True),
        sa.Column("macro_type", sa.String(), nullable=True),
        sa.Column("execution_count", sa.Integer(), nullable=True),
        sa.Column("processed_files_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "creation_month",
            "macro_type",
            name="unique_macro_summary",
        ),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_macro_execution_summary_creation_month"),
        "macro_execution_summary",
        ["creation_month"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_macro_execution_summary_organization_id"),
        "macro_execution_summary",
        ["organization_id"],
        unique=False,
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cognition_macro_execution_summary_organization_id"),
        table_name="macro_execution_summary",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_macro_execution_summary_creation_month"),
        table_name="macro_execution_summary",
        schema="cognition",
    )
    op.drop_table("macro_execution_summary", schema="cognition")
    # ### end Alembic commands ###
