"""Adds tmp file indicators


Revision ID: c43adf0a6d08
Revises: 4861b97fcd5d
Create Date: 2024-04-03 12:04:17.717913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c43adf0a6d08'
down_revision = '4861b97fcd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('has_tmp_files', sa.Boolean(), nullable=True), schema='cognition')
    op.add_column('conversation', sa.Column('archived', sa.Boolean(), nullable=True), schema='cognition')
    op.add_column('project', sa.Column('allow_file_upload', sa.Boolean(), nullable=True), schema='cognition')
    op.add_column('project', sa.Column('max_file_size_mb', sa.Float(), nullable=True), schema='cognition')
    op.add_column('project', sa.Column('open_ai_env_var_id', postgresql.UUID(as_uuid=True), nullable=True), schema='cognition')
    op.create_foreign_key("project_env_var_id_fkey", "project", "environment_variable", ["open_ai_env_var_id"], ["id"], ondelete="SET NULL", schema='cognition'),
    op.create_index(op.f("ix_project_env_var_id"), "project", ["open_ai_env_var_id"], unique=False, schema="cognition")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'allow_file_upload', schema='cognition')
    op.drop_column('project', 'max_file_size_mb', schema='cognition')
    op.drop_column('project', 'open_ai_env_var_id', schema='cognition')
    op.drop_column('conversation', 'has_tmp_files', schema='cognition')
    op.drop_column('conversation', 'archived', schema='cognition')

    op.drop_index(op.f("ix_project_env_var_id"), table_name="project", schema="cognition")
    op.drop_constraint("project_env_var_id_fkey", "project", type_="foreignkey")
    # ### end Alembic commands ###
