"""add

Revision ID: c626887031f6
Revises: 11675e102ac4
Create Date: 2024-10-15 13:53:26.632068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c626887031f6'
down_revision = '11675e102ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_reference', sa.Column('last_used', sa.DateTime(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_reference', 'last_used', schema='cognition')
    # ### end Alembic commands ###
