"""Dummy alembic to update incognito

Revision ID: c6d1cbcccb41
Revises: 059f0d62a6b9
Create Date: 2025-10-27 15:38:06.608300

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6d1cbcccb41"
down_revision = "059f0d62a6b9"
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    update_dataset_sql = """
        UPDATE cognition.conversation
        SET incognito_mode = FALSE
        WHERE incognito_mode IS NULL; """
    connection.execute(update_dataset_sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
