"""add routing config

Revision ID: c80e536fb9d7
Revises: 1e2359bf1fbc
Create Date: 2024-08-19 18:31:47.376137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80e536fb9d7'
down_revision = '1e2359bf1fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('operator_routing_config', sa.JSON(), nullable=True), schema='cognition')
    op.drop_column('project', 'operator_routing_source_code', schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('operator_routing_source_code', sa.VARCHAR(), autoincrement=False, nullable=True), schema='cognition')
    op.drop_column('project', 'operator_routing_config', schema='cognition')
    # ### end Alembic commands ###
