"""Rename working on

Revision ID: c95b049b0779
Revises: 094dd28a1d8d
Create Date: 2025-11-17 10:58:16.971432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95b049b0779'
down_revision = '094dd28a1d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail_thread', sa.Column('is_in_progress', sa.Boolean(), nullable=True), schema='global')
    op.drop_column('inbox_mail_thread', 'being_working_on', schema='global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail_thread', sa.Column('being_working_on', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='global')
    op.drop_column('inbox_mail_thread', 'is_in_progress', schema='global')
    # ### end Alembic commands ###
