"""Progress state inbox mial thread

Revision ID: cbc8f102510c
Revises: 8b89db0d41fd
Create Date: 2025-11-18 14:23:36.853407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbc8f102510c'
down_revision = '8b89db0d41fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail_thread', sa.Column('progress_state', sa.String(), nullable=True), schema='global')
    op.add_column('inbox_mail_thread', sa.Column('support_owner_id', postgresql.UUID(as_uuid=True), nullable=True), schema='global')
    op.create_index(op.f('ix_global_inbox_mail_thread_support_owner_id'), 'inbox_mail_thread', ['support_owner_id'], unique=False, schema='global')
    op.create_foreign_key(None, 'inbox_mail_thread', 'user', ['support_owner_id'], ['id'], source_schema='global', ondelete='SET NULL')
    op.drop_column('inbox_mail_thread', 'is_in_progress', schema='global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_mail_thread', sa.Column('is_in_progress', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='global')
    op.drop_constraint(None, 'inbox_mail_thread', schema='global', type_='foreignkey')
    op.drop_index(op.f('ix_global_inbox_mail_thread_support_owner_id'), table_name='inbox_mail_thread', schema='global')
    op.drop_column('inbox_mail_thread', 'support_owner_id', schema='global')
    op.drop_column('inbox_mail_thread', 'progress_state', schema='global')
    # ### end Alembic commands ###
