"""Restructure inbox mail threads

Revision ID: d02bf381e3ed
Revises: b59188cf5526
Create Date: 2025-11-15 18:44:47.229926

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d02bf381e3ed"
down_revision = "b59188cf5526"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_mail_thread",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("participant_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("is_important", sa.Boolean(), nullable=True),
        sa.Column("being_working_on", sa.Boolean(), nullable=True),
        sa.Column("is_admin_support_thread", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        "idx_inbox_thread_participants_gin",
        "inbox_mail_thread",
        ["participant_ids"],
        unique=False,
        schema="global",
        postgresql_using="gin",
        postgresql_ops={"participant_ids": "array_ops"},
    )
    op.create_index(
        op.f("ix_global_inbox_mail_thread_organization_id"),
        "inbox_mail_thread",
        ["organization_id"],
        unique=False,
        schema="global",
    )
    op.drop_index(
        "ix_global_inbox_mail_reference_inbox_mail_id",
        table_name="inbox_mail_reference",
        schema="global",
    )
    op.drop_index(
        "ix_global_inbox_mail_reference_user_id",
        table_name="inbox_mail_reference",
        schema="global",
    )
    op.drop_table("inbox_mail_reference", schema="global")
    op.drop_index(
        "ix_global_inbox_mail_organization_id", table_name="inbox_mail", schema="global"
    )
    op.drop_index(
        "ix_global_inbox_mail_parent_id", table_name="inbox_mail", schema="global"
    )
    op.drop_constraint(
        "inbox_mail_parent_id_fkey", "inbox_mail", schema="global", type_="foreignkey"
    )
    op.drop_constraint(
        "inbox_mail_organization_id_fkey",
        "inbox_mail",
        schema="global",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "inbox_mail",
        "inbox_mail_thread",
        ["thread_id"],
        ["id"],
        source_schema="global",
        referent_schema="global",
        ondelete="CASCADE",
    )
    op.drop_column("inbox_mail", "being_working_on", schema="global")
    op.drop_column("inbox_mail", "original_recipient_ids", schema="global")
    op.drop_column("inbox_mail", "organization_id", schema="global")
    op.drop_column("inbox_mail", "parent_id", schema="global")
    op.drop_column("inbox_mail", "subject", schema="global")
    op.drop_column("inbox_mail", "is_important", schema="global")
    op.drop_column("inbox_mail", "meta_data", schema="global")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inbox_mail",
        sa.Column(
            "meta_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        schema="global",
    )
    op.add_column(
        "inbox_mail",
        sa.Column("is_important", sa.BOOLEAN(), autoincrement=False, nullable=True),
        schema="global",
    )
    op.add_column(
        "inbox_mail",
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="global",
    )
    op.add_column(
        "inbox_mail",
        sa.Column("parent_id", postgresql.UUID(), autoincrement=False, nullable=True),
        schema="global",
    )
    op.add_column(
        "inbox_mail",
        sa.Column(
            "organization_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        schema="global",
    )
    op.add_column(
        "inbox_mail",
        sa.Column(
            "original_recipient_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        schema="global",
    )
    op.add_column(
        "inbox_mail",
        sa.Column("being_working_on", sa.BOOLEAN(), autoincrement=False, nullable=True),
        schema="global",
    )
    op.drop_constraint(
        "inbox_mail_thread_id_fkey",
        "inbox_mail",
        schema="global",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "inbox_mail_organization_id_fkey",
        "inbox_mail",
        "organization",
        ["organization_id"],
        ["id"],
        source_schema="global",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "inbox_mail_parent_id_fkey",
        "inbox_mail",
        "inbox_mail",
        ["parent_id"],
        ["id"],
        source_schema="global",
        referent_schema="global",
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_global_inbox_mail_parent_id",
        "inbox_mail",
        ["parent_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        "ix_global_inbox_mail_organization_id",
        "inbox_mail",
        ["organization_id"],
        unique=False,
        schema="global",
    )
    op.create_table(
        "inbox_mail_reference",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "inbox_mail_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("scope", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_seen", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["inbox_mail_id"],
            ["global.inbox_mail.id"],
            name="inbox_mail_reference_inbox_mail_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="inbox_mail_reference_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="inbox_mail_reference_pkey"),
        schema="global",
    )
    op.create_index(
        "ix_global_inbox_mail_reference_user_id",
        "inbox_mail_reference",
        ["user_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        "ix_global_inbox_mail_reference_inbox_mail_id",
        "inbox_mail_reference",
        ["inbox_mail_id"],
        unique=False,
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_thread_organization_id"),
        table_name="inbox_mail_thread",
        schema="global",
    )
    op.drop_index(
        "idx_inbox_thread_participants_gin",
        table_name="inbox_mail_thread",
        schema="global",
        postgresql_using="gin",
        postgresql_ops={"participant_ids": "array_ops"},
    )
    op.drop_table("inbox_mail_thread", schema="global")
    # ### end Alembic commands ###
