"""adds web integrations

Revision ID: d454676ee76f
Revises: 1133d27823e3
Create Date: 2026-03-03 16:51:11.127269

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d454676ee76f"
down_revision = "1133d27823e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webpage",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("integration_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("running_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("minio_file_name", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("extension", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("raw_markdown_content_hash", sa.String(), nullable=True),
        sa.Column("etag", sa.String(), nullable=True),
        sa.Column("last_modified", sa.String(), nullable=True),
        sa.Column("etl_task_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["etl_task_id"], ["global.etl_task.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"], ["cognition.integration.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "integration_id", "source", "etl_task_id", name="unique_webpage_source"
        ),
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_webpage_created_by"),
        "webpage",
        ["created_by"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_webpage_etl_task_id"),
        "webpage",
        ["etl_task_id"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_webpage_integration_id"),
        "webpage",
        ["integration_id"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_webpage_running_id"),
        "webpage",
        ["running_id"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_webpage_source"),
        "webpage",
        ["source"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_webpage_updated_by"),
        "webpage",
        ["updated_by"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_sharepoint_object_id"),
        "sharepoint",
        ["object_id"],
        unique=False,
        schema="integration",
    )
    op.create_unique_constraint(
        "unique_sharepoint_object_id",
        "sharepoint",
        ["integration_id", "running_id", "object_id", "etl_task_id"],
        schema="integration",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_sharepoint_object_id",
        "sharepoint",
        schema="integration",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_integration_sharepoint_object_id"),
        table_name="sharepoint",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_webpage_updated_by"),
        table_name="webpage",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_webpage_source"),
        table_name="webpage",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_webpage_running_id"),
        table_name="webpage",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_webpage_integration_id"),
        table_name="webpage",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_webpage_etl_task_id"),
        table_name="webpage",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_webpage_created_by"),
        table_name="webpage",
        schema="integration",
    )
    op.drop_table("webpage", schema="integration")
    # ### end Alembic commands ###
