"""Key support for upload

Revision ID: d4f77b59f4a4
Revises: 03d19eada266
Create Date: 2023-06-21 11:30:41.032489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f77b59f4a4'
down_revision = '03d19eada266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_task', sa.Column('key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_task', 'key')
    # ### end Alembic commands ###
