"""Add column for attribute visibility

Revision ID: da902ad27b4a
Revises: f803a0c4343c
Create Date: 2022-12-02 09:36:36.431815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da902ad27b4a"
down_revision = "f803a0c4343c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attribute", sa.Column("visibility", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attribute", "visibility")
    # ### end Alembic commands ###
