"""Add integration record refinery sync

Revision ID: dbb8ee9f98d2
Revises: 3483b60b25e4
Create Date: 2026-01-15 10:32:43.789166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb8ee9f98d2'
down_revision = '3483b60b25e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharepoint', sa.Column('refinery_synced', sa.Boolean(), nullable=True), schema='integration')
    op.add_column('webpage', sa.Column('refinery_synced', sa.Boolean(), nullable=True), schema='integration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webpage', 'refinery_synced', schema='integration')
    op.drop_column('sharepoint', 'refinery_synced', schema='integration')
    # ### end Alembic commands ###
