"""adds tier to cognition project

Revision ID: dcf231fee37f
Revises: 7edb03b88c03
Create Date: 2024-05-04 12:39:15.241482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf231fee37f'
down_revision = '7edb03b88c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("tier", sa.Integer(), nullable=True),
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "tier", schema="cognition")
    # ### end Alembic commands ###
