"""adds sharepoint_property_sync table

Revision ID: de396670d10f
Revises: 312568866ac4
Create Date: 2025-09-04 16:53:25.748371

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de396670d10f"
down_revision = "312568866ac4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sharepoint_property_sync",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("integration_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("logs", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["integration_id"], ["cognition.integration.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id"),
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_sharepoint_property_sync_created_by"),
        "sharepoint_property_sync",
        ["created_by"],
        unique=False,
        schema="integration",
    )
    op.create_index(
        op.f("ix_integration_sharepoint_property_sync_integration_id"),
        "sharepoint_property_sync",
        ["integration_id"],
        unique=False,
        schema="integration",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_integration_sharepoint_property_sync_integration_id"),
        table_name="sharepoint_property_sync",
        schema="integration",
    )
    op.drop_index(
        op.f("ix_integration_sharepoint_property_sync_created_by"),
        table_name="sharepoint_property_sync",
        schema="integration",
    )
    op.drop_table("sharepoint_property_sync", schema="integration")
    # ### end Alembic commands ###
