"""adds relations table

Revision ID: de7ab206cc46
Revises: 6b7c123b3e52
Create Date: 2024-02-25 19:53:57.185727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7ab206cc46'
down_revision = '6b7c123b3e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column(
            "relations", sa.ARRAY(sa.JSON()), autoincrement=False, nullable=True
        ),
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "relations", schema="cognition")
    # ### end Alembic commands ###
