"""adds allow_microsoft_copilot_connection

Revision ID: e08f38f06e98
Revises: 1133d27823e3
Create Date: 2026-02-26 09:48:58.048211

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e08f38f06e98"
down_revision = "1133d27823e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("allow_microsoft_copilot_connection", sa.Boolean(), nullable=True),
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "allow_microsoft_copilot_connection", schema="cognition")
    # ### end Alembic commands ###
