"""Added LLM config

Revision ID: e0fa50dd6350
Revises: 54a5713f7de7
Create Date: 2024-06-17 16:00:18.053487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fa50dd6350'
down_revision = '54a5713f7de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markdown_dataset', sa.Column('llm_config', sa.JSON(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markdown_dataset', 'llm_config', schema='cognition')
    # ### end Alembic commands ###
