"""One drive path for desktop version

Revision ID: e3e108cd4b22
Revises: 04cd434ed6eb
Create Date: 2025-12-10 15:30:56.732793

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3e108cd4b22"
down_revision = "04cd434ed6eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("one_drive_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "one_drive_path")
    # ### end Alembic commands ###
