"""adds consumption summary

Revision ID: e8575fcc5cac
Revises: 1e96826f3bd8
Create Date: 2024-03-20 08:29:51.220966

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e8575fcc5cac"
down_revision = "1e96826f3bd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumption_summary",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("project_name", sa.String(), nullable=True),
        sa.Column("complexity", sa.String(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["cognition.project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "project_id", "date", "complexity", name="unique_summary"
        ),
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_consumption_summary_date"),
        "consumption_summary",
        ["date"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_consumption_summary_organization_id"),
        "consumption_summary",
        ["organization_id"],
        unique=False,
        schema="cognition",
    )
    op.create_index(
        op.f("ix_cognition_consumption_summary_project_id"),
        "consumption_summary",
        ["project_id"],
        unique=False,
        schema="cognition",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cognition_consumption_summary_project_id"),
        table_name="consumption_summary",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_consumption_summary_organization_id"),
        table_name="consumption_summary",
        schema="cognition",
    )
    op.drop_index(
        op.f("ix_cognition_consumption_summary_date"),
        table_name="consumption_summary",
        schema="cognition",
    )
    op.drop_table("consumption_summary", schema="cognition")
    # ### end Alembic commands ###
