"""Added full admin table

Revision ID: eb96f9b82cc1
Revises: 455cb5890ac1
Create Date: 2025-04-24 09:12:33.200446

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eb96f9b82cc1"
down_revision = "455cb5890ac1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "full_admin_access",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("meta_info", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="global",
    )

    op.execute(
        """
        INSERT INTO global.full_admin_access (id, email, meta_info)
        VALUES
            (gen_random_uuid(), 'lina.lumburovska@kern.ai','{}'),
            (gen_random_uuid(), 'jens.wittmeyer@kern.ai','{}'),
            (gen_random_uuid(), 'lennart.schmidt@kern.ai','{}'),
            (gen_random_uuid(), 'anmar.hindi@kern.ai','{}'),
            (gen_random_uuid(), 'andrea.hrelja@kern.ai','{}'),
            (gen_random_uuid(), 'leonard.puettmann@kern.ai','{}'),
            (gen_random_uuid(), 'johannes.hoetter@kern.ai','{}'),
            (gen_random_uuid(), 'henrik.wenck@kern.ai','{}'),
            (gen_random_uuid(), 'jason.wirth@kern.ai','{}')
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("full_admin_access", schema="global")
    # ### end Alembic commands ###
