"""Inbox mail table

Revision ID: ebf4435d83f8
Revises: 85bb3ebee137
Create Date: 2025-11-06 13:44:57.938408

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ebf4435d83f8"
down_revision = "85bb3ebee137"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_mail",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("send_from", sa.String(), nullable=True),
        sa.Column("send_to", sa.JSON(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("mark_as_important", sa.Boolean(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("is_seen", sa.Boolean(), nullable=True),
        sa.Column("being_worked_on", sa.Boolean(), nullable=True),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("child_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"], ["global.inbox_mail.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["global.inbox_mail.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_child_id"),
        "inbox_mail",
        ["child_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_organization_id"),
        "inbox_mail",
        ["organization_id"],
        unique=False,
        schema="global",
    )
    op.create_index(
        op.f("ix_global_inbox_mail_parent_id"),
        "inbox_mail",
        ["parent_id"],
        unique=False,
        schema="global",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_global_inbox_mail_parent_id"), table_name="inbox_mail", schema="global"
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_organization_id"),
        table_name="inbox_mail",
        schema="global",
    )
    op.drop_index(
        op.f("ix_global_inbox_mail_child_id"), table_name="inbox_mail", schema="global"
    )
    op.drop_table("inbox_mail", schema="global")
    # ### end Alembic commands ###
