"""Adds comment table and role/org management columns

Revision ID: f61b26e09e8c
Revises: 5b3a4deea1c4
Create Date: 2022-09-14 09:08:50.746833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f61b26e09e8c"
down_revision = "5b3a4deea1c4"
branch_labels = None
depends_on = None


def upgrade():

    op.create_table(
        "comment",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("xfkey", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("xftype", sa.String(), nullable=True),
        sa.Column("add_key", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("is_markdown", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_comment_xftype", "comment", ["xftype"], unique=False)
    op.create_index("ix_comment_xfkey", "comment", ["xfkey"], unique=False)
    op.create_index("ix_comment_project_id", "comment", ["project_id"], unique=False)
    op.create_index("ix_comment_created_by", "comment", ["created_by"], unique=False)

    op.add_column("organization", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("organization", sa.Column("is_paying", sa.Boolean(), nullable=True))
    op.add_column("organization", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("role", sa.String(), nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    op.drop_column("organization", "created_at")
    op.drop_column("organization", "is_paying")
    op.drop_column("organization", "started_at")
    op.drop_index("ix_comment_created_by", table_name="comment")
    op.drop_index("ix_comment_project_id", table_name="comment")
    op.drop_index("ix_comment_xfkey", table_name="comment")
    op.drop_index("ix_comment_xftype", table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
