"""add group metadata

Revision ID: f75bfdd547f3
Revises: 4da42978f669
Create Date: 2025-06-19 22:55:22.603225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75bfdd547f3'
down_revision = '4da42978f669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('meta_data', sa.JSON(), nullable=True), schema='cognition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'meta_data', schema='cognition')
    # ### end Alembic commands ###
