"""Adds personal-access-token-table

Revision ID: f803a0c4343c
Revises: 09311360f8b9
Create Date: 2022-11-23 13:50:24.978181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f803a0c4343c'
down_revision = '09311360f8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_access_token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_access_token_project_id'), 'personal_access_token', ['project_id'], unique=False)
    op.create_index(op.f('ix_personal_access_token_user_id'), 'personal_access_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_access_token_user_id'), table_name='personal_access_token')
    op.drop_index(op.f('ix_personal_access_token_project_id'), table_name='personal_access_token')
    op.drop_table('personal_access_token')
    # ### end Alembic commands ###
