from typing import Any, Dict, List, Optional
from submodules.model.business_objects import general, user
from submodules.model.global_objects import inbox_mail
from submodules.model.util import sql_alchemy_to_dict
from controller.auth import kratos
from sqlalchemy.orm.attributes import flag_modified

DEFAULT_KERN_AI_ADMIN_NAME = {"first": "Kern AI Support", "last": ""}
DEFAULT_SYSTEM_AUTOGENERATED_NAME = {"first": "System", "last": ""}


def create_inbox_mail_by_thread(
    org_id: str,
    sender_id: str,
    recipient_ids: List[str],
    subject: str,
    content: str,
    is_important: bool = False,
    is_admin_support_thread: bool = False,
    meta_data: Optional[Dict[str, Any]] = None,
    thread_id: Optional[str] = None,
) -> Dict[str, Any]:

    return inbox_mail.create_by_thread(
        org_id=org_id,
        sender_id=sender_id,
        content=content,
        recipient_ids=recipient_ids,
        subject=subject,
        meta_data=meta_data,
        thread_id=thread_id,
        is_important=is_important,
        is_admin_support_thread=is_admin_support_thread,
    )


def get_inbox_mails_by_thread(
    org_id: str,
    user_id: str,
    thread_id: Optional[str] = None,
    user_is_admin: bool = False,
) -> List[Dict[str, Any]]:
    mails = inbox_mail.get_by_thread(
        org_id, user_id, thread_id, user_is_admin=user_is_admin
    )
    participant_ids = [
        str(pid) for pid in inbox_mail.get_participant_ids_by_thread_id(thread_id)
    ]
    admin_user_ids = [str(u.id) for u in user.get_admin_users()]

    mail_dicts = [sql_alchemy_to_dict(mail) for mail in mails]
    thread_entity = inbox_mail.get_inbox_mail_thread_by_id(thread_id)
    thread_association = (
        inbox_mail.get_inbox_mail_thread_association_by_thread_id_and_user_id(
            thread_id, user_id
        )
    )
    if thread_association:
        thread_association.unread_mail_count = 0
        general.flush_or_commit(True)
    if thread_entity and thread_entity.is_admin_support_thread:
        meta_data = thread_entity.meta_data or {}
        if user_id in admin_user_ids:
            if meta_data.get("unreadMailCountAdmin", 0) > 0:
                meta_data["unreadMailCountAdmin"] = 0
                thread_entity.meta_data = meta_data
                flag_modified(thread_entity, "meta_data")
                general.flush_or_commit(True)
    for mail_dict in mail_dicts:
        extend_inbox_mail_sender_receiver_names(
            participant_ids=participant_ids,
            mail_dict=mail_dict,
            user_id=user_id,
            admin_user_ids=admin_user_ids,
            is_admin_support_thread=(
                thread_entity.is_admin_support_thread if thread_entity else False
            ),
            is_auto_generated=thread_entity.meta_data.get("autoGenerated", False),
        )
    return mail_dicts


def get_inbox_mail_threads_overview(
    org_id: str,
    user_id: str,
    page: int = 1,
    limit: int = 10,
    user_is_admin: bool = False,
) -> Dict[str, Any]:
    overview_by_threads = inbox_mail.get_overview_by_threads(
        org_id=org_id,
        user_id=user_id,
        page=page,
        limit=limit,
        user_is_admin=user_is_admin,
    )

    admin_user_ids = [str(u.id) for u in user.get_admin_users()]

    for thread in overview_by_threads["threads"]:
        if not thread.get("latest_mail"):
            continue
        if not user_is_admin:
            thread.pop("meta_data", None)

        extend_inbox_mail_sender_receiver_names(
            participant_ids=thread["participant_ids"],
            mail_dict=thread["latest_mail"],
            user_id=user_id,
            admin_user_ids=admin_user_ids,
            is_admin_support_thread=thread.get("is_admin_support_thread", False),
            is_auto_generated=thread.get("meta_data", {}).get("autoGenerated", False),
        )

    return overview_by_threads


def create_auto_generated_inbox_mail_thread_for_error(
    org_id: str,
    created_by: str,
    subject: str,
    content: str,
    is_important: bool = False,
    meta_data: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:

    inbox_mail.create_by_thread(
        org_id=org_id,
        sender_id=None,
        content=content,
        recipient_ids=[],
        subject=subject,
        meta_data=meta_data,
        thread_id=None,
        is_important=is_important,
        created_by=created_by,
        is_admin_support_thread=True,
    )


def get_new_inbox_mails_info(
    org_id: str, user_id: str, user_is_admin: bool
) -> Dict[str, int]:
    return inbox_mail.get_new_inbox_mails(
        org_id=org_id, user_id=user_id, user_is_admin=user_is_admin
    )


def extend_inbox_mail_sender_receiver_names(
    participant_ids: List[str],
    mail_dict: Dict[str, Any],
    user_id: str,
    admin_user_ids: list[str],
    is_admin_support_thread: bool = False,
    is_auto_generated: bool = False,
) -> None:

    recipient_ids = [
        rid for rid in participant_ids if str(rid) != str(mail_dict.get("sender_id"))
    ]
    if not is_admin_support_thread:
        mail_dict["senderName"] = kratos.resolve_user_name_by_id(mail_dict["sender_id"])
        mail_dict["recipientNames"] = [
            kratos.resolve_user_name_by_id(rid) for rid in recipient_ids
        ]
        return

    user_is_admin = str(user_id) in admin_user_ids
    user_is_sender = str(user_id) == str(mail_dict["sender_id"])
    sender_is_admin = str(mail_dict["sender_id"]) in admin_user_ids
    if is_auto_generated and user_is_admin:

        if not (mail_dict.get("sender_id")):
            mail_dict["senderName"] = DEFAULT_SYSTEM_AUTOGENERATED_NAME
            mail_dict["recipientNames"] = [DEFAULT_KERN_AI_ADMIN_NAME]
        else:
            mail_dict["senderName"] = DEFAULT_KERN_AI_ADMIN_NAME
            mail_dict["recipientNames"] = [DEFAULT_SYSTEM_AUTOGENERATED_NAME]
        return
    if (user_is_sender and not user_is_admin) or (
        user_is_admin and not sender_is_admin
    ):
        mail_dict["senderName"] = kratos.resolve_user_name_by_id(mail_dict["sender_id"])
        mail_dict["recipientNames"] = [DEFAULT_KERN_AI_ADMIN_NAME]

    elif not user_is_sender and not user_is_admin:
        mail_dict["senderName"] = DEFAULT_KERN_AI_ADMIN_NAME
        mail_dict["recipientNames"] = [
            kratos.resolve_user_name_by_id(rid) for rid in recipient_ids
        ]
    elif user_is_admin and user_is_sender and user_id in participant_ids:
        mail_dict["senderName"] = kratos.resolve_user_name_by_id(mail_dict["sender_id"])
        mail_dict["recipientNames"] = [DEFAULT_KERN_AI_ADMIN_NAME]
    elif user_is_admin and sender_is_admin:
        mail_dict["senderName"] = DEFAULT_KERN_AI_ADMIN_NAME
        mail_dict["recipientNames"] = [
            kratos.resolve_user_name_by_id(rid) for rid in recipient_ids
        ]
