from enum import Enum


class LabelStudioTypes(Enum):
    CHOICES = "choices"
    LABELS = "labels"
    MANUAL = "manual"
    PROTECTED_COLUMN = "PROTECTED_COLUMN"
    DATA_COLUMN = "DATA_COLUMN"
    ANNOTATION_COLUMN_EXTRACTION = "ANNOTATION_COLUMN_EXTRACTION"
    ANNOTATION_COLUMN_CLASSIFICATION = "ANNOTATION_COLUMN_CLASSIFICATION"
